apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: speakup

resources:
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - services.yaml
  - config.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: speakup
  app.kubernetes.io/managed-by: kustomize
